# Generated by Django 3.2.12 on 2025-03-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('waste_type', models.CharField(choices=[('Plastic', 'Plastic'), ('Organic', 'Organic'), ('Metal', 'Metal'), ('Glass', 'Glass'), ('Paper', 'Paper'), ('Cardboard', 'Cardboard'), ('Trash', 'Trash')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
